apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-api-sa
  namespace: target-namespace
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-dashboard-sa
  namespace: attacker-namespace
automountServiceAccountToken: false